name: responsive_utility
description: "A comprehensive utility package for creating responsive UIs in Flutter."
version: 0.0.3
homepage: "https://github.com/ashwinsevak1808/flutter_responsive_utils" # Replace this URL with your package's homepage URL

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Metadata for the pub.dev
repository: "https://github.com/ashwinsevak1808/flutter_responsive_utils" # Replace with your repository URL
issue_tracker: "https://github.com/ashwinsevak1808/flutter_responsive_utils/issues" # Replace with your issue tracker URL

# Flutter-specific configuration

# Other configuration...

# Flutter-specific configuration
flutter:
  # Specify the files to include in the package
  assets:
    - lib/src/linear_widget.dart
    - lib/src/linear_direction.dart

# Other metadata...

# Other metadata
# These fields are optional but can be useful for users of your package
# for finding and understanding the purpose of your package.

# Keywords that describe your package
keywords:
  - flutter
  - responsive
  - utils
  - UI
  - package

# Categories under which your package falls
categories:
  - libraries
  - tools
  - UI components

# Links to documentation
documentation: "https://github.com/ashwinsevak1808/flutter_responsive_utils/wiki" # Replace with your documentation URL

# License details
# Include the license file in your package
license: "MIT" # Specify your chosen license, and include a LICENSE file in your project
